/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javaa_native_JNI */

#ifndef _Included_javaa_native_JNI
#define _Included_javaa_native_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javaa_native_JNI
 * Method:    dajKomandu
 * Signature: (Ljava/lang/String;CLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javaa_1native_JNI_dajKomandu
  (JNIEnv *, jobject, jstring, jchar, jstring, jstring);

/*
 * Class:     javaa_native_JNI
 * Method:    citajTabele
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javaa_1native_JNI_citajTabele
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
